{{- if .Values.mssql.developerEdition }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-mssql-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.saPassword }}
  SA_PASSWORD: {{ default "" .Values.saPassword | b64enc | quote }}
  {{ else }}
  SA_PASSWORD: {{ randAlphaNum 13 | b64enc | quote }}
  {{ end }}
{{ end }}